= To-Do list of Black Flag
:author: Marcos Cruz (programandala.net)
:revdate: 2019-03-21

== 2019-03-21

- Make `sea`, `island`, and `visited` byte arrays.
- Check the logic of `trade` at the end: its last word is
  `one-coin-less`.
- Fix: since v0.71.0 the intro texts are corrupted.
- Fix/Improve: relation of `found-clues` and `native-tells-clue`, with
  the total score.

== 2019-03-20

- Check usage of map offset, e.g. `to-north`.
- Fix: after the embarking after the trade, the next scenary is still
  the island.
- Store common attributes in constants.
- Shorten "intenta bloquear el paso" and other texts.
- Sound effect in `attack-native`.
- Fix: Redraw the panel after killing a native, to update the
  shortcut.
- Improve: The more pacific natives are killed on the island, the more
  difficult will be the trading.
- Fix calculation: After offering 6 dubloons instead of 9, the native
  asks for 6.
- Fix the logic: Now the village can be attacked again and again,
  without advantage. Besides, the trading is still possible...
- Improve: Make all pauses with `?seconds`.

== 2019-03-19

- Fix: Deactivate trading if the village has been attacked.
- Remove `do-attack-boat` and everything related.
- Fix the map of the treasure island.
- Reembark when the treasure has not been found.
- Improve layout of `score-report`.
- Fix: Some texts don't fit in `native-window` and overwrite the
  start.
- Create a "…" character and use it instead of "..." to save some
  space in the texts.

== 2017-02-02, 2017-02-04

Improve: Move all string literals to far memory. This step will be
needed to add more languages anyway.

== 2017-02-02

Improve: Count storms and adapt the warning accordingly.

== 2017-02-02

Improve: Reduce the storm probability after every storm.

== 2017-02-02

Improve the random position of the clouds: Make them move only one
column right or left.

== 2017-02-01

Improve: To save some memory, store conditions in tittle case and
convert them with `lowers` when needed, not the other way around. This
would save `uppers1`, which depends on `upper`, which has been moved
to the library of Solo Forth.

== 2017-01-23

Improve: Print the ship in two colors.

== 2017-01-22

Fix: The disembarking command is available is location that have no
island.

== 2017-01-22

Fix: When ammo is finished during the ship battle, the message is
shown as a pop-up.

Solution 1: Restore the previous screen first (the sea scenery).

Solution 2: Redesign the screen of the ship battle and reserve a
window for messages. This window can be used for other new messages as
well.

== 2017-01-22

Improve: Access all reports (a menu) with one key in the panel.

== 2017-01-21, 2019-03-20

Move the `name` double-cell array to far memory.

2019-03-20: It was tried, but since `far2variable`, `far2@` and
`far2!` are needed only for this, there's no gain:

|===
| Free memory space | Before | After | Difference

| data/code         |   1811 |  1792 |        -19
| name              |  36591 | 36513 |        -78
|===

== 2017-01-21

Add 128K sound effects.

== 2017-01-21, 2017-11-28

Wait for the space key after the reports, to prevent the key from
activating a new panel command?

== 2017-01-12

Move the palms into the word of their islands.

== 2017-01-10, 2017-01-18

Combine all graphics into one single UDG set:

-  95 chars from graph font 1
-  67 chars from graph font 2
-  21 UDG
-  16 block chars (perhaps not all of them are used)

Total: 199 characters

|===
| Character codes  | Origin

| 0..31            | graph font 2
| 32..127          | graph font 1
| 128..143         | block chars
| 144..164         | UDG set
| 165..198         | graph font 2
|===

Only the strings printed with graph font 2 must be adapted.

== 2017-01-08, 2019-03-19

Convert maps to character arrays in far memory, to save memory.

== Old notes about the abandaned conversion to Master BASIC

NOTE: The following notes from the abandoned Master BASIC version are
still useful for the Forth version.

Desligar los valores en `seaMap` e `islandMap` de los objetos que
contienen (monedas, tiburón, barco enemigo, nativo...). Guardarlos en
una matriz independiente. Esto hará más claros los algoritmos y
evitará el problema de que la pantalla se redibuja cuando desaparece
un objeto (p.e., las monedas) tan solo porque ha cambiado el valor de
esa celda del mapa.

Tabla de mejores puntuaciones.

Hacer dos aspectos para el final: éxito y fracaso.

Hacer, si no está, que se reciban provisiones, munición y tropa tras
vencer a un barco.

Dibujar escorpión y pantano.

Poder matar escorpión.

Borrar serpiente y escorpión cuando mueran.

Hacer variable el dibujo de provisiones.

Reducir moral unas décimas cuando un hombre sea herido o muerto.

Reducir la energía un número proporcional a la gravedad del ataque, no
siempre 1.

Informar de que no se puede desembarcar porque la isla ya ha sido
visitada.

Revisar los rangos de doblones al comerciar.

Añadir «Fin» a la lista de comandos.
