= To-Do list of Bandera Negra
:author: Marcos Cruz (programandala.net)
:revdate: 2016-12-18

== New notes about the conversion to Forth

- Convert `let`.
- Review variables and constants.
- Convert `if`.
- Convert `plot` and `draw`.

== Old notes (in Spanish) from the abandoned Master BASIC version
  
Desligar los valores en seaMap and islandMap de los objetos que
contienen (monedas, tiburón, barco enemigo, nativo...). Guardarlos en
una matriz independiente. Esto hará más claros los algoritmos y
evitará el problema de que la pantalla se redibuja cuando desaparece
un objeto (p.e., las monedas) tan solo porque ha cambiado el valor de
esa celda del mapa.

Condiciones para los comandos del panel: 

Comerciar: `islandMap(iPos)=nativeVillage`

Matar: `not(islandMap(iPos)=2 or islandMap(iPos)=4 or islandMap(iPos)=6)`

Cambiar la medida del daño del barco (variable «damage») por su
estado, analógamente a la tripulación, y mostrarlo en forma de texto.

Tabla de mejores puntuaciones; guardada en disquete.

Hacer dos aspectos para el final: éxito y fracaso.

Ampliar fn number$() y usarla en la negociación.

Un programa herramienta que prepare y guarde las matrices en el
disquete, para que el juego se ahorre la tarea, el código y el tiempo.
(Quizá no merece la pena, porque hay variables que definir también y
deberían duplicarse en ambos programas).

Hacer que el número de doblones hallados varíe.

Usar un juego de caracteres diferente para las palabras de los
nativos.

Hacer, si no está, que se reciban provisiones, munición y tropa tras
vencer a un barco.

Dibujar escorpión y pantano.

Poder matar escorpión.

Borrar serpiente y escorpión cuando mueran.

Hacer variable el dibujo de provisiones.

Poner la pista en el bocadillo.

Reducir moral unas décimas cuando un hombre sea herido o muerto.

Reducir la energía un número proporcional a la gravedad del ataque, no
siempre 1.

Informar de que no se puede desembarcar porque la isla ya ha sido
visitada.

Fallo: el barco sale con fondo negro cuando encalla.

Revisar los rangos de doblones al comerciar.

Informar de si hay muertos cuando el bote es alcanzado por error.
Calcular 'alive' antes y después de herir a los hombres.

Usar otro juego de caracteres.

Hacer que el jugador pueda poner nombre a los miembros de la
tripulación.

Cambiar el aspecto de las pantallas finales: negras y con calaveras.

Hacer que el jugador pueda elegir nombre al capitán. 

Añadir Fin a la lista de comandos

Al embarcar, borrar panel antes de redibujar pantalla.

Hacer que el sol se imprima también al azar, pero no coincida con las
nubes.
