= To-Do list of Bandera Negra
:author: Marcos Cruz (programandala.net)
:revdate: 2017-01-12

== New notes about the conversion to Forth

- Review variables and constants.
- Convert `beep`.
- Convert `goto` and `label`.
- Wait for the space key after the reports, to prevent the key to
  activate a command after returning to the panel.

.2017-01-12:

Change `." X"` (4 bytes) to `'X' emit` (5 bytes) in some places,
because it's faster.

.2017-01-10:

Combine all graphics into one single UDG set:

- 95 chars from graph font 1
- 95 chars from graph font 2
- -1 (space common to both graph fonts)
- 21 UDG
- 16 block chars (perhaps not all of them are used)
- -1 useless empty block char

Total: 225 characters

|===
| Character codes  | Origin

| 32..127          | graph font 1
| 128              | *not used*
| 129..143         | block chars
| 144..164         | UDG set
|===

The strings printed with graph font 2 must be changed:


.2017-01-08:

Simplify the ship damage calculations: Use only one counter and one
range.

.2017-01-08:

Convert `used-name`, `stamina` and maps to a character array, to save
memory.

.2017-01-08:

Remove `graphic-window`.

.2017-01-08:

Convert `possible-north` flag and family to calculations.

== Old notes (in Spanish) from the abandoned Master BASIC version

Desligar los valores en `seaMap` e `islandMap` de los objetos que
contienen (monedas, tiburón, barco enemigo, nativo...). Guardarlos en
una matriz independiente. Esto hará más claros los algoritmos y
evitará el problema de que la pantalla se redibuja cuando desaparece
un objeto (p.e., las monedas) tan solo porque ha cambiado el valor de
esa celda del mapa.

Condiciones para los comandos del panel:

- Comerciar: `islandMap(iPos)=nativeVillage`
- Matar: `not(islandMap(iPos)=2 or islandMap(iPos)=4 or
  islandMap(iPos)=6)`

Cambiar la medida del daño del barco (variable `damage`) por su
estado, analógamente a la tripulación, y mostrarlo en forma de texto.

Tabla de mejores puntuaciones.

Hacer dos aspectos para el final: éxito y fracaso.

Ampliar `fn number$()` y usarla en la negociación.

Hacer que el número de doblones hallados varíe.

Usar un juego de caracteres diferente para las palabras de los
nativos.

Hacer, si no está, que se reciban provisiones, munición y tropa tras
vencer a un barco.

Dibujar escorpión y pantano.

Poder matar escorpión.

Borrar serpiente y escorpión cuando mueran.

Hacer variable el dibujo de provisiones.

Poner la pista en el bocadillo.

Reducir moral unas décimas cuando un hombre sea herido o muerto.

Reducir la energía un número proporcional a la gravedad del ataque, no
siempre 1.

Informar de que no se puede desembarcar porque la isla ya ha sido
visitada.

Fallo: el barco sale con fondo negro cuando encalla.

Revisar los rangos de doblones al comerciar.

Informar de si hay muertos cuando el bote es alcanzado por error.
Calcular `alive` antes y después de herir a los hombres.

Hacer que el jugador pueda poner nombre a los miembros de la
tripulación.

Cambiar el aspecto de las pantallas finales: negras y con calaveras.

Hacer que el jugador pueda elegir nombre al capitán.

Añadir «Fin» a la lista de comandos.

Al embarcar, borrar panel antes de redibujar pantalla.

Hacer que el sol se imprima también al azar, pero no coincida con las
nubes.
