= To-Do list of Black Flag
:author: Marcos Cruz (programandala.net)
:revdate: 2019-03-19

== 2019-03-19

Rewrite `trigger` with a calculation and a vector table.

== 2017-11-29

Check `score +!`: it should not be used in `update-score`; beside,
it's used already in some events.

== 2017-02-04, 2018-04-30

Fix the crashes when entering the island locations that have 3 palms.
The problem seems related to the fact that there's no event in those
locations, and the stack gets unbalanced.

The checks in `island-location` confirm the crash can happen in
locations `just-3-palms-1` and `just-3-palms-2`, but not always.

== 2017-02-02, 2017-02-04

Improve: Move all string literals to far memory. This step will be
needed to add more languages anyway.

== 2017-02-02

Improve: Count storms and adapt the warning accordingly.

== 2017-02-02

Improve: Reduce the storm probability after every storm.

== 2017-02-02

Improve the random position of the clouds: Make them move only one
column right or left.

== 2017-02-01

Improve: To save some memory, store conditions in tittle case and
convert them with `lowers` when needed, not the other way around. This
would save `uppers1`, which depends on `upper`, which has been moved
to the library of Solo Forth.

== 2017-01-23

Improve: Print the ship in two colors.

== 2017-01-22

Fix: The disembarking command is available is location that have no
island.

== 2017-01-22

Fix: When ammo is finished during the ship battle, the message is
shown as a pop-up.

Solution 1: Restore the previous screen first (the sea scenery).

Solution 2: Redesign the screen of the ship battle and reserve a
window for messages. This window can be used for other new messages as
well.

== 2017-01-22

Improve: Access all reports (a menu) with one key in the panel.

== 2017-01-21

Move the `name` double-cell array to far memory.

== 2017-01-21

Add 128K sound effects.

== 2017-01-21, 2017-11-28

Wait for the space key after the reports, to prevent the key from
activating a new panel command?

== 2017-01-12

Move the palms into the word of their islands.

== 2017-01-10, 2017-01-18

Combine all graphics into one single UDG set:

-  95 chars from graph font 1
-  67 chars from graph font 2
-  21 UDG
-  16 block chars (perhaps not all of them are used)

Total: 199 characters

|===
| Character codes  | Origin

| 0..31            | graph font 2
| 32..127          | graph font 1
| 128..143         | block chars
| 144..164         | UDG set
| 165..198         | graph font 2
|===

Only the strings printed with graph font 2 must be adapted.

== 2017-01-08

Simplify the ship damage calculations: Use only one counter and one
range.

== 2017-01-08

Convert `used-name`, `stamina` and maps to a character array, to save
memory.

== Old notes about the abandaned conversion to Master BASIC

NOTE: The following notes from the abandoned Master BASIC version are
still useful for the Forth version.

Desligar los valores en `seaMap` e `islandMap` de los objetos que
contienen (monedas, tiburón, barco enemigo, nativo...). Guardarlos en
una matriz independiente. Esto hará más claros los algoritmos y
evitará el problema de que la pantalla se redibuja cuando desaparece
un objeto (p.e., las monedas) tan solo porque ha cambiado el valor de
esa celda del mapa.

Tabla de mejores puntuaciones.

Hacer dos aspectos para el final: éxito y fracaso.

Ampliar `fn number$()` y usarla en la negociación.

Hacer, si no está, que se reciban provisiones, munición y tropa tras
vencer a un barco.

Dibujar escorpión y pantano.

Poder matar escorpión.

Borrar serpiente y escorpión cuando mueran.

Hacer variable el dibujo de provisiones.

Poner la pista en el bocadillo.

Reducir moral unas décimas cuando un hombre sea herido o muerto.

Reducir la energía un número proporcional a la gravedad del ataque, no
siempre 1.

Informar de que no se puede desembarcar porque la isla ya ha sido
visitada.

Revisar los rangos de doblones al comerciar.

Informar de si hay muertos cuando el bote es alcanzado por error.
Calcular `alive` antes y después de herir a los hombres.

Hacer que el jugador pueda poner nombre a los miembros de la
tripulación.

Hacer que el jugador pueda elegir nombre al capitán.

Añadir «Fin» a la lista de comandos.
